### ISSUE TITLE
Jüngste Änderung am Global Cache in ILIAS 7 verhindert LiveVoting-Betrieb

### ISSUE THREAD

**Issue by bogenschlag** [livevoting-ilias/LiveVoting#2]
Fabians Commit [74f550299351881b233ef57e90880484d4d02a60](https://github.com/ILIAS-eLearning/ILIAS/commit/74f550299351881b233ef57e90880484d4d02a60) scheint dazu zu führen, dass das LV crasht und sich Container-Objekte mit LV-Objekten darin nicht mehr öffnen lassen:

```
Whoops\Exception\ErrorException thrown with message "Declaration of LiveVoting\Cache\Version\v52\xlvoCache::lookupServiceClassName($service_type) must be compatible with ilGlobalCache::lookupServiceClassName(int $service_type): string"

Stacktrace:
#2 Whoops\Exception\ErrorException in /srv/www/vhosts/ilias3.uni-stuttgart.de/Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/src/Cache/Version/v52/xlvoCache.php:121
#1 Whoops\Run:handleError in /srv/www/vhosts/ilias3.uni-stuttgart.de/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:486
#0 Whoops\Run:handleShutdown in [internal]:0
```

**Comment by okaufman** [comment]
Gerade eben hat Fabian Schmid diese Änderung wieder rückgängig gemacht.
https://github.com/ILIAS-eLearning/ILIAS/commit/a57f5f8f709cf8b14c9d7a4d150c9feeab36808f 
Wir müssen also mit dieser neusten Änderung das Plugin nicht anpassen.
